"""5_add_price_model

Revision ID: 018307f68d3d
Revises: 1fd9d11e3118
Create Date: 2023-09-20 10:58:18.178894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018307f68d3d'
down_revision = '1fd9d11e3118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=11, scale=6), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index('idx_date_tickerid', ['date', 'ticker_id'], unique=False)
        batch_op.create_index('idx_tickerid_date', ['ticker_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index('idx_tickerid_date')
        batch_op.drop_index('idx_date_tickerid')

    op.drop_table('prices')
    # ### end Alembic commands ###
