"""10_change_trade_date_type

Revision ID: 12c6cc725a77
Revises: 43a219a67f18
Create Date: 2023-10-10 15:40:06.455238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c6cc725a77'
down_revision = '43a219a67f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.alter_column('trade_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.alter_column('trade_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
