"""6_add_last_trade_column

Revision ID: 14581731c7bf
Revises: 018307f68d3d
Create Date: 2023-09-22 10:03:36.664498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14581731c7bf'
down_revision = '018307f68d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_last_trade', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('is_last_trade')

    # ### end Alembic commands ###
