"""4_correct_ondelete_typo

Revision ID: 1fd9d11e3118
Revises: 6a1ce24b7955
Create Date: 2023-09-15 15:53:53.931561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd9d11e3118'
down_revision = '6a1ce24b7955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_constraint('watchlist_items_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'watchlists', ['watchlist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_constraint('watchlists_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('watchlists_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('watchlist_items_ibfk_2', 'watchlists', ['watchlist_id'], ['id'])

    # ### end Alembic commands ###
