"""1_initial_migration

Revision ID: 65baca3a01f5
Revises: 
Create Date: 2023-09-04 14:36:16.709872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65baca3a01f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column(
            'id', 
            sa.Integer(),
            autoincrement=True, 
            nullable=False),
        sa.Column(
            'username', 
            sa.String(length=25), 
            nullable=False
        ),
        sa.Column(
            'password', 
            sa.String(length=257), 
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_users_username'),
            ['username'],
            unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
