"""7_remove_sector_column

Revision ID: d6270e38275d
Revises: 14581731c7bf
Create Date: 2023-09-28 14:39:47.300086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6270e38275d'
down_revision = '14581731c7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('sector')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
